server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "123456"
    name: "bit303_shop"
    debug: true

gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/bit303_shop"
        tables: "employee_info,employee_points_account,employee_points_record,goods_category,goods_info,cart_info"
        path: "./internal"
