// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IMiddleware interface {
		ResponseHandler(r *ghttp.Request)
		Ctx(r *ghttp.Request)
		CORS(r *ghttp.Request)
		Auth(r *ghttp.Request)
		UserAuth(r *ghttp.Request)
		GTokenSetCtx(r *ghttp.Request)
		// PermissionCheck 权限校验中间件
		PermissionCheck(r *ghttp.Request)
	}
)

var (
	localMiddleware IMiddleware
)

func Middleware() IMiddleware {
	if localMiddleware == nil {
		panic("implement not found for interface IMiddleware, forgot register?")
	}
	return localMiddleware
}

func RegisterMiddleware(i IMiddleware) {
	localMiddleware = i
}
