// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"bit303_shop/internal/model"
)

type (
	IPraise interface {
		AddPraise(ctx context.Context, in model.AddPraiseInput) (res *model.AddPraiseOutput, err error)
		DeletePraise(ctx context.Context, in model.DeletePraiseInput) (res *model.DeletePraiseOutput, err error)
		GetList(ctx context.Context, in model.PraiseListInput) (out *model.PraiseListOutput, err error)
		// 获取点赞数量
		PraiseCount(ctx context.Context, objectId uint, collectionType uint8) (count int, err error)
		// 判断当前用户是否点赞
		CheckIsPraise(ctx context.Context, in model.CheckIsCollectInput) (bool, error)
	}
)

var (
	localPraise IPraise
)

func Praise() IPraise {
	if localPraise == nil {
		panic("implement not found for interface IPraise, forgot register?")
	}
	return localPraise
}

func RegisterPraise(i IPraise) {
	localPraise = i
}
