// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"bit303_shop/internal/model"

	"golang.org/x/net/context"
)

type (
	IRole interface {
		Create(ctx context.Context, in model.RoleCreateInput) (out model.RoleCreateOutput, err error)
		AddPermission(ctx context.Context, in model.RoleAddPermissionInput) (out model.RoleAddPermissionOutput, err error)
		AddPermissions(ctx context.Context, roleId uint, permissionIds []uint) error
		Delete(ctx context.Context, id uint) error
		DeletePermission(ctx context.Context, in model.RoleDeletePermissionInput) error
		DeletePermissions(ctx context.Context, roleId uint, permissionIds []uint) error
		Update(ctx context.Context, in model.RoleUpdateInput) error
		GetList(ctx context.Context, in model.RoleGetListInput) (out *model.RoleGetListOutput, err error)
		GetPermissionsByRoleId(ctx context.Context, roleId uint) ([]model.RolePermissionItem, error)
	}
)

var (
	localRole IRole
)

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
