// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"bit303_shop/internal/model"
)

type (
	IUser interface {
		Register(ctx context.Context, in model.RegisterInput) (out model.RegisterOutput, err error)
		UpdatePassword(ctx context.Context, in model.UpdatePasswordInput) (out model.UpdatePasswordOutput, err error)
		// 后台管理接口
		GetList(ctx context.Context, in model.UserGetListInput) (out *model.UserGetListOutput, err error)
		UpdateStatus(ctx context.Context, id uint, status int) error
		Delete(ctx context.Context, id uint) error
		GetById(ctx context.Context, id uint) (*model.UserInfoItem, error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
