// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// adminRoleRelationDao is the data access object for the table admin_role_relation.
// You can define custom methods on it to extend its functionality as needed.
type adminRoleRelationDao struct {
	*internal.AdminRoleRelationDao
}

var (
	// AdminRoleRelation is a globally accessible object for table admin_role_relation operations.
	AdminRoleRelation = adminRoleRelationDao{internal.NewAdminRoleRelationDao()}
)

// Add your custom methods and functionality below.
