// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// adminRolePermissionDao is the data access object for the table admin_role_permission.
// You can define custom methods on it to extend its functionality as needed.
type adminRolePermissionDao struct {
	*internal.AdminRolePermissionDao
}

var (
	// AdminRolePermission is a globally accessible object for table admin_role_permission operations.
	AdminRolePermission = adminRolePermissionDao{internal.NewAdminRolePermissionDao()}
)

// Add your custom methods and functionality below.
