// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// adminPermissionDao is the data access object for the table admin_permission.
// You can define custom methods on it to extend its functionality as needed.
type adminPermissionDao struct {
	*internal.AdminPermissionDao
}

var (
	// AdminPermission is a globally accessible object for table admin_permission operations.
	AdminPermission = adminPermissionDao{internal.NewAdminPermissionDao()}
)

// Add your custom methods and functionality below.
