// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// employeePointsAccountDao is the data access object for the table employee_points_account.
// You can define custom methods on it to extend its functionality as needed.
type employeePointsAccountDao struct {
	*internal.EmployeePointsAccountDao
}

var (
	// EmployeePointsAccount is a globally accessible object for table employee_points_account operations.
	EmployeePointsAccount = employeePointsAccountDao{internal.NewEmployeePointsAccountDao()}
)

// Add your custom methods and functionality below.
