// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// employeeInfoDao is the data access object for the table employee_info.
// You can define custom methods on it to extend its functionality as needed.
type employeeInfoDao struct {
	*internal.EmployeeInfoDao
}

var (
	// EmployeeInfo is a globally accessible object for table employee_info operations.
	EmployeeInfo = employeeInfoDao{internal.NewEmployeeInfoDao()}
)

// Add your custom methods and functionality below.
