// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// employeePointsRecordDao is the data access object for the table employee_points_record.
// You can define custom methods on it to extend its functionality as needed.
type employeePointsRecordDao struct {
	*internal.EmployeePointsRecordDao
}

var (
	// EmployeePointsRecord is a globally accessible object for table employee_points_record operations.
	EmployeePointsRecord = employeePointsRecordDao{internal.NewEmployeePointsRecordDao()}
)

// Add your custom methods and functionality below.
