// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// goodsCategoryDao is the data access object for the table goods_category.
// You can define custom methods on it to extend its functionality as needed.
type goodsCategoryDao struct {
	*internal.GoodsCategoryDao
}

var (
	// GoodsCategory is a globally accessible object for table goods_category operations.
	GoodsCategory = goodsCategoryDao{internal.NewGoodsCategoryDao()}
)

// Add your custom methods and functionality below.
