// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// goodsStockRecordDao is the data access object for the table goods_stock_record.
// You can define custom methods on it to extend its functionality as needed.
type goodsStockRecordDao struct {
	*internal.GoodsStockRecordDao
}

var (
	// GoodsStockRecord is a globally accessible object for table goods_stock_record operations.
	GoodsStockRecord = goodsStockRecordDao{internal.NewGoodsStockRecordDao()}
)

// Add your custom methods and functionality below.
