// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// internalSeckillGoodsDao is internal type for wrapping internal DAO implements.
type internalSeckillGoodsDao = *internal.SeckillGoodsDao

// seckillGoodsDao is the data access object for table seckill_goods.
// You can define custom methods on it to extend its functionality as you wish.
type seckillGoodsDao struct {
	internalSeckillGoodsDao
}

var (
	// SeckillGoods is globally public accessible object for table seckill_goods operations.
	SeckillGoods = seckillGoodsDao{
		internal.NewSeckillGoodsDao(),
	}
)

// Fill with you ideas below.
