// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// internalSeckillOrderDao is internal type for wrapping internal DAO implements.
type internalSeckillOrderDao = *internal.SeckillOrderDao

// seckillOrderDao is the data access object for table seckill_order.
// You can define custom methods on it to extend its functionality as you wish.
type seckillOrderDao struct {
	internalSeckillOrderDao
}

var (
	// SeckillOrder is globally public accessible object for table seckill_order operations.
	SeckillOrder = seckillOrderDao{
		internal.NewSeckillOrderDao(),
	}
)

// Fill with you ideas below.
