// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bit303_shop/internal/dao/internal"
)

// uploadFileDao is the data access object for the table upload_file.
// You can define custom methods on it to extend its functionality as needed.
type uploadFileDao struct {
	*internal.UploadFileDao
}

var (
	// UploadFile is a globally accessible object for table upload_file operations.
	UploadFile = uploadFileDao{internal.NewUploadFileDao()}
)

// Add your custom methods and functionality below.
