server:
  address: ":8001"  # 使用不同端口避免与主服务冲突

# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]
 
  default:
  # todo 修改成自己的密码
    link: "mysql:root:111111@tcp(127.0.0.1:3306)/shop"
    debug: true
    maxIdle: 10
    maxOpen: 100
    maxLifetime: 30

# Redis 配置
redis:
  default:
    address: 127.0.0.1:6379
    db: 1
    pass: "123456"
    idleTimeout: 60
    maxIdle: 5
    maxActive: 10
    dialTimeout: 1
    readTimeout: 1
    writeTimeout: 1
    waitTimeout: 1

# Kafka 配置
mq:
  kafka:
    brokers: ["localhost:9092"]
    producer:
      retryMax: 3
      timeout: 5
      batchSize: 100
      batchTimeout: "100ms"
      requiredAcks: "all"
    consumer:
      group: "seckill-test-group"
      topics: ["seckill-order"]
      offsetReset: "latest"
      maxWaitTime: "1s"
      minBytes: 1
      maxBytes: 10485760 